CREATE TABLE `places` (
	`id` text PRIMARY KEY,
	`name` text NOT NULL,
	`localName` text,
	`category` text,
	`categories` text,
	`description` text,
	`latitude` real NOT NULL,
	`longitude` real NOT NULL,
	`timezone` text,
	`address` text,
	`street` text,
	`district` text,
	`city` text,
	`postalCode` text,
	`country` text,
	`phone` text,
	`website` text,
	`logo` text,
	`rating` real,
	`reviews` integer,
	`price` text,
	`hours` text,
	`services` text,
	`accessible` integer,
	`reserve` text,
	`sponsored` integer,
	`image` text
);
