import { type Place } from "../_types/place";

export const places: Place[] = [
  {
    name: "Bonnie - Goulash & Langosh Bar",
    rating: 4.7,
    reviews: "18,233",
    category: "Hungarian restaurant",
    address: "5 Ferenciek tere",
    hours: { status: "Open", detail: "Closes 12 am", color: "#198639" },
    sponsored: true,
    services: [
      { label: "Dine-in", available: true },
      { label: "Takeaway", available: true },
      { label: "Delivery", available: true },
    ],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEsn4VA2h3WU7MBSsJL3uFB63jm8_kvoyJYf7dR9YOGm4O-QSBffjibt8AiUhChjK92kO8KAY9yuaDcLcjXVeMTTNes303vKozphN95i9riOigkD_nPYf0GhEjaGWcbMthg2hpsDW1cD9yW",
  },
  {
    name: "Halászbástya Étterem",
    rating: 4.4,
    reviews: "1,353",
    price: "$$$$",
    category: "Restaurant",
    address: "Budapest Budai Vár, Halászbástya - Északi Híradástorony",
    hours: { status: "Opens soon", detail: "6 pm", color: "#b26c00" },
    sponsored: true,
    services: [
      { label: "Dine-in", available: true },
      { label: "Takeaway", available: true },
      { label: "Delivery", available: false },
    ],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAE87VVywbELYlI0SbXDVZrkfjMe2vaX6lggYk_fgGDejtutK9dpylh9_6mXn2bz-nyi_yevDmvNR-7Myg34b7CL0cMbQFD9Y1gayUR6bq1cMO0apcOQ1CKuOJFk-s_dmn8u_4ru9iqrmWM",
  },
  {
    name: "Mazel Tov",
    accessible: true,
    rating: 4.6,
    reviews: "40,571",
    price: "6 000–18 000 Ft",
    category: "Israeli",
    address: "Akácfa u. 47",
    description: "Modern cafe bar & cultural venue",
    hours: { status: "Open", detail: "Closes 11 pm", color: "#198639" },
    review: "\"Everything from the service to the quality of food and drinks was top notch.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHbIGuyzvuQK38xftHe9d0853otL82rh4NcOKb8uIxqi5XNSPrl8jI8F1wWR6kqpn5oXLxEz93mn1Mc5r-6QTX2hdexS0ZOwjMWvo4zyOZMs2FSKlCQx3vPADLZGt6LbYiJlypa",
  },
  {
    name: "Comme Chez Soi",
    rating: 4.7,
    reviews: "3,934",
    price: "8 000–20 000 Ft",
    category: "Restaurant",
    address: "Aranykéz u. 2",
    hours: { status: "Open", detail: "Closes 11 pm", color: "#198639" },
    review: "\"In summary: incredible food, excellent service, and a cozy, welcoming vibe.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFt5FYCGpjIgccICaKl0Jm8gPErlZ7yFC9okAkZOm4ZP1QmTVqsNacDclQhPIynphwddx7z9WobBytuwnp3MBBfOF8cI_JfXg5VqS5afhMbtoMZjXLBY5Rq7Cd1lXxE3qGE25OckQ",
  },
  {
    name: "Aranybástya",
    reserve: true,
    rating: 4.8,
    reviews: "2,890",
    category: "Restaurant",
    address: "Buda Castle, Csónak u. 1",
    hours: { status: "Open", detail: "Closes 10 pm", color: "#198639" },
    review: "\"The atmosphere was relaxing, the food delicious, and the service excellent.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHGAdgGi-Y8LZVJsWFVLyDPGYwH8qErQ1f3xX86GnZuzBp3kDg4zWPxbYJF_sJxN-wHKLIp8qg10d7mHTW1dAOgfLXNn-5hnlGQNuOSJjhd-ZQRuShZmX15i0cSAzKnEa5GIXqNM00cEDOZ",
  },
  {
    name: "Pilvax Kávéház és Étterem",
    accessible: true,
    rating: 4.9,
    reviews: "2,070",
    price: "6 000–16 000 Ft",
    category: "Hungarian",
    address: "Pilvax köz 3",
    hours: { status: "Open", detail: "Closes 11 pm", color: "#198639" },
    review: "\"Amazing atmosphere, amazing service, and delicious food!\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEX8DDg7pUGn0kwGiDyi4cjYc3e-NbXHwjtcYfUJPaYg0v96VFF1Eepw2XM6KWcfWUXnj58MBx4A4EZFkJIi8b5ODlANQh_p300RrfRW741EiVLBzJBETBfpttpy4prZuJXdLLi",
  },
  {
    name: "Trattoria Pomo D'Oro",
    accessible: true,
    rating: 4.7,
    reviews: "13,365",
    price: "$$$",
    category: "Italian",
    address: "Arany János u. 9",
    description: "Rustic venue for high-end Italian dishes",
    hours: { status: "Open", detail: "Closes 11 pm", color: "#198639" },
    review: "\"Attentive service, amazing pasta dishes and winter-themed drinks.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHGYxLYWYK3VtJPgo9PN2mXXkyWp19fYa_EScgdeRmgOGDlXoD8kTOFXgPGaRrmUngiPhmk2t2t79NhsmzyprCTs_X2a78krowOHGk2zvcoJzna5CJLMeyx-pCGXx-QkkX32Lqy",
  },
  {
    name: "Parasztkonyha Restaurant",
    rating: 4.8,
    reviews: "9,906",
    price: "6 000–18 000 Ft",
    category: "Hungarian",
    address: "Október 6. u. 3",
    hours: { status: "Open", detail: "Closes 11 pm", color: "#198639" },
    review: "\"Exceptional food, and Jenci was very kind and served us impeccably.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHEtCtiqFVdQNI2avpUf5OSU1lbh9M6LmOnNW62FuOZ0iNKikCvrKFxNKLa-PKBhIbtCNoRb18fMPZQ2CNRv4THgEkWpimX5bmFp-PZDR0aqWD7wiLtTOh-uvSIwb_ZGZEvnIx9Uw",
  },
  {
    name: "Bob's Kitchen Budapest",
    reserve: true,
    rating: 4.8,
    reviews: "648",
    price: "4 000–14 000 Ft",
    category: "Restaurant",
    address: "Paulay Ede u. 16",
    hours: { status: "Open", detail: "Closes 10 pm", color: "#198639" },
    review: "\"Great food, wonderful atmosphere, attentive & friendly staff.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGXWC7r6ad910IR7FRih08zZG7XcpT2F8WKXK0ROV7G7qvovxfxYHBQ7183FpSG-EkfRnBVkIL04GGYbp_hnjvWGZxXTMVu6eLHXu75zrCQX6JclZt3ickuNGN8pvBaK8jDpRG0ynHbwuGR",
  },
  {
    name: "Fleischer Restobar",
    accessible: true,
    rating: 4.8,
    reviews: "941",
    category: "Restaurant",
    address: "Nagymező u. 7",
    hours: { status: "Open", detail: "Closes 11:30 pm", color: "#198639" },
    review: "\"Wow wow wow, the food, the service, the drinks, it was all perfect!\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAE4qVTQwqkZcdVAUNXjNvM_f1uKFoUlsh45vA4xVaEE0ir2VQZGIigliaJhj0TQt8XykdWpk2vkP8oB90K4f3Qv52nAWWhSNohnLMfyHLJ35U28wf5nKQLGcqHn0ybewllzf0Rh",
  },
  {
    name: "KOLLÁZS - Brasserie & Bar",
    reserve: true,
    accessible: true,
    rating: 4.6,
    reviews: "1,986",
    price: "20 000 Ft+",
    category: "Modern European",
    address: "Széchenyi István tér 5-6",
    hours: { status: "Open", detail: "Closes 12 am", color: "#198639" },
    review: "\"From the food to the service to the ambience it was flawless!\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH_kLVdZK_en9DIyLgcNPV_d9cZgaQ4dIYatJKWdD1fnY37vjhDs6TZNRalNOocLVotfSYu1NzHwly3qvnqzVhi_FaIrtpaif8yYWCeT9gXO-ShatI6xfgI289OBG2WqVzTH-sx",
  },
  {
    name: "Dobrumba",
    accessible: true,
    rating: 4.5,
    reviews: "5,089",
    price: "4 000–12 000 Ft",
    category: "Restaurant",
    address: "Dob u. 5",
    description: "Down-home option for global fare",
    hours: { status: "Open", detail: "Closes 11:30 pm", color: "#198639" },
    review: "\"The food and wine was great, fun and casual vibe and awesome service.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEYLVkCjAGX78NJ2KNaYZqGuS4IWFNdLnxUjaOY0XoK18PRbwZFgPSkKj4oKvcBUCLSmON2fzZH7cAJg7OXaHjjcsF0FAIynwO2jNwtStf4QEitGTmNEuwa8bs-EurTaUHHpUBiPQ",
  },
  {
    name: "Hell's Kitchen – Hungarian Restaurant",
    reserve: true,
    accessible: true,
    rating: 4.7,
    reviews: "11,793",
    price: "6 000–18 000 Ft",
    category: "Hungarian",
    address: "Kígyó u. 4",
    hours: { status: "Open", detail: "Closes 11 pm", color: "#198639" },
    review: "\"The food, the atmosphere and drinks were very very very exceptional.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFgqnG4lLgDMwYjQuyd9jziG09PxIbBBo0Q0NvQyglmZOdHIfSEfiYj6y_QKv6ArIAl83cgYH3tdh4NSGy-FFAI8M-KWFCeKXoifAM2Ly9VnB_btR2Iapd6XPzwBse_yOOnfctXLw",
  },
  {
    name: "Restaurante Fuego",
    accessible: true,
    rating: 4.6,
    reviews: "9,086",
    price: "4 000–12 000 Ft",
    category: "Grill",
    address: "Kazinczy u. 3b",
    hours: { status: "Open", detail: "Closes 11:30 pm", color: "#198639" },
    review: "\"Food was delicious, service was great and a nice chilled atmosphere.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGXPAfBfvqxkvyd7tMOPDenuLvd9meLgbZgLDJQNkjMNnZoNInGnPwpe7rHMh0W-RRGlpOqb-ol3JbL54tyKrGm6mQjGqRINA8UzputSrAAbP_-wV3XSso4L8kzfLX-WxuHUvqm",
  },
  {
    name: "Szaletly",
    accessible: true,
    rating: 4.7,
    reviews: "3,925",
    price: "$$$",
    category: "Restaurant",
    address: "Stefánia út 93",
    hours: { status: "Open", detail: "Closes 11 pm", color: "#198639" },
    review: "\"Wow, great food, beautiful interior, and loved the live music.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHI7y5rMDIS6RD-3ucXlicgjR7rcUoHLsmKpabLQaJVA1RzLwg_wByo74BPoA1mq5ba_kmn7TuR6EbqaXrAlEaARmV1Ab5LGYS_BqxH1EsjYzj9so0lmgsz5FlSkbbT077CFXki",
  },
  {
    name: "Beerstro14 Steak House Restaurant",
    reserve: true,
    rating: 4.9,
    reviews: "12,186",
    price: "20 000 Ft+",
    category: "Steak",
    address: "Károlyi utca 12",
    description: "Hip venue for craft brews & meaty eats",
    hours: { status: "Open", detail: "Closes 11 pm", color: "#198639" },
    review: "\"Our food was delicious and the beer and wine selection were first class.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHSgeq50la4bvnVdb6RriaZF56BOGd3wlg93RizrM6M7OCHfVnbtL59FXiwKmszWlTxkx1CmGhCiN6F5Q_3Qr5f2TkgsXPG2vuMW1OMcrB87OP5ziVSKX3pjjgtPqbsDw4BI7I",
  },
  {
    name: "Mazi Greek Kitchen",
    reserve: true,
    accessible: true,
    rating: 4.7,
    reviews: "3,886",
    price: "6 000–14 000 Ft",
    category: "Greek",
    address: "Alkotmány u 19",
    hours: { status: "Open", detail: "Closes 11 pm", color: "#198639" },
    review: "\"Delicious food and incredible service from our charming waiter, Symeon.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHW5c7xIvQ7uCdhRdQfmkA5gaEsrW8OZjnrUK2qs62OEkagDKGpvFkMa3J7Yn_m-RXt6gRkjVk1ib5ycXcZzRUA-ySzHXspPOhgeP8hdHbWDfKabnCL2QKTl1cU7ug1QxOfr2XL",
  },
  {
    name: "Royal Guard Cafe",
    reserve: true,
    rating: 4.7,
    reviews: "1,795",
    category: "Restaurant",
    address: "Palota Hunyadi-udvar",
    hours: { status: "Open", detail: "Closes 11 pm", color: "#198639" },
    review: "\"Everything we ordered was fresh, flavorful, and beautifully presented.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGvpGN3XFSfqMopuMUreLnzYddMt--H_2MwYYWcjq-VUgTUCA-j9bW7a4Gf8rAVuMCZyPUnTy41nrQHSxiBOcUZzQ5h3V3Q4fbZIZLOKLCyU85BUQA89XdWHWlPFHkoqYhG18T3",
  },
  {
    name: "Rosenstein Vendéglő",
    accessible: true,
    rating: 4.6,
    reviews: "4,473",
    price: "8 000–20 000 Ft",
    category: "Hungarian",
    address: "Mosonyi u. 3",
    description: "Homely venue for Hungarian cuisine",
    hours: { status: "Open", detail: "Closes 11 pm", color: "#198639" },
    review: "\"Excellent, delicious food in pleasant atmosphere and outstanding service!\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFFsXf69GyUBXlj8oJDveRO1Nu2_GYYTfZuLTTzbQ4Zi6N9UTPUAqfAL_mPx4lzbBzPOhoDzAWS8rESyG0YS10UyEgMVqONUStOOF3JFrNbfhj7wfa3f1CGCBFgrBELM9a5cAEykmwiqLQB",
  },
  {
    name: "Ropogós Bistro & Garden",
    accessible: true,
    rating: 4.8,
    reviews: "1,510",
    price: "8 000–18 000 Ft",
    category: "Bistro",
    address: "Rákosi út 9",
    hours: { status: "Open", detail: "Closes 10 pm", color: "#198639" },
    review: "\"Polite, professional and friendly staff, food is high quality.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGH0KQqNNhL9VCeBRKJrv7c3ZTa8RZaChgKcOUXGeWXIDpFgmV2Uu7jLOC8zLBJat2O4vnnZW0lVfkdGDZ0oc62UC4CInWk6xsU9h93KIv6-VHqwIBOQDs-Us_7nG8XL7sxdIU",
  },
  {
    name: "Városliget Café",
    reserve: true,
    accessible: true,
    rating: 4.7,
    reviews: "5,174",
    price: "$$",
    category: "Restaurant",
    address: "Olof Palme stny. 6",
    description: "Classic option for local specialties",
    hours: { status: "Open", detail: "Closes 10 pm", color: "#198639" },
    review: "\"The atmosphere is great, the staff are attentive, and the food is delicious.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH9ghHw2EmjBYLwt8H9DjtNN1iEq-45-ykFEAIV_qAO0vf9STVbR7mM51dRznZhZlkIxYu6GvVVGZm38usN7mvFDnGMMA25FqIYrKfPSXApBk3zhzgay9inaE_G1kdyjbZOgx7GdWnMd6R2",
  },
  {
    name: "Baalbek Restaurant",
    accessible: true,
    rating: 4.6,
    reviews: "2,823",
    price: "$$",
    category: "Lebanese",
    address: "Belgrád rkp. 22",
    hours: { status: "Open", detail: "Closes 12 am", color: "#198639" },
    review: "\"Service was amazing, food was lovely, and atmosphere was relaxing.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHvu8Vr-s4KFCOgJs0Wu6f2HU2aYh0NZSXmx-jS5kLsNRGoeqaTVkYsrKDNzHSKaropJOi6e6JY0yVf2hsduTfoofIsGNKHFyI7gPMkgq4B_umPTvA4f3vhyiu-M42dyN7zCiUIZg",
  },
  {
    name: "The Diner Co. by Felisa - American Bar & Restaurant",
    reserve: true,
    rating: 4.9,
    reviews: "1,212",
    price: "6 000–16 000 Ft",
    category: "Restaurant",
    address: "Zrínyi u. 18",
    hours: { status: "Open", detail: "Closes 11 pm", color: "#198639" },
    review: "\"Great service, delicious rib stack burger!\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGo9243o4Kj6MgWtsyzpM1_R2DrozQGPZL7RkmRc-uvlnZgW4j_eA2W_zPxWSSM02YA6MDpyp_cqSfRNfO58wKcpidzjUp7mMbzZbAantIdj6a_HKfa4qlljrXmRPbPb7ozWInzX9s1vSY",
  },
  {
    name: "Tapassio",
    rating: 4.8,
    reviews: "2,785",
    price: "$$",
    category: "Tapas",
    address: "Hercegprímás u. 13",
    hours: { status: "Open", detail: "Closes 12 am", color: "#198639" },
    review: "\"Extremely good service, great wine and cocktails, and super delicious food.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFY45jbLuZ1ULPLjDgETsOrvbYMMHPn2wHM3sU7NI0FDpq4iD2Nht2NL8nCaf9pa1oRhJzP6Ua2IqTer9K0jB0t9HGUYvC9r4rxVhnLv3CFUO7ShTTZHxd5F-WgOrJOdYienj9MpA",
  },
  {
    name: "Millennium Kávéház és Étterem",
    reserve: true,
    rating: 4.6,
    reviews: "929",
    price: "2 000–14 000 Ft",
    category: "Restaurant",
    address: "Olof Palme stny. 1",
    description: "Elegant eatery with imaginative fare",
    hours: { status: "Open", detail: "Closes 8 pm", color: "#198639" },
    review: "\"Chill atmosphere, professional staff great food!\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFJsJm9yvdklPav_fb2Fua2_gb2-KgLlzgmGYpmD6K2g26AoZ_kkBmL3bC1VaKISnytgmaX-PHUMClnykLqIheJA4ZsS7m47XtAZ15YQ9Sxi4UFnWahVmi1GZe0-D8tajvSjgYv",
  },
  {
    name: "He He Chinese Restaurant",
    rating: 4.4,
    reviews: "858",
    price: "4 000–6 000 Ft",
    category: "Restaurant",
    address: "1101 Budapest, Monori u. 2-4, E7",
    hours: { status: "Open", detail: "Closes 9 pm", color: "#198639" },
    review: "\"Incredible food - friendly staff.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHlucT0kAwOHZr7VYztB9QtXNaX3xbL2eCrVDKpAmYcX8OZV6T5983Mio774YXob6STrhtNCrfgq-yagnKyv-SPngdqzXClhDiWnzl6_6c2PoLsnmztCcDI2HfW-jTG0xWqIzU",
  },
  {
    name: "Dionysos Taverna",
    rating: 4.8,
    reviews: "8,947",
    price: "$$$",
    category: "Greek",
    address: "Belgrád rkp. 16",
    description: "Quaint restaurant for Greek cuisine",
    hours: { status: "Open", detail: "Closes 12 am", color: "#198639" },
    review: "\"The atmosphere, the food, and the friendly service were all wonderful.\"",
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEuDYt_yHuzHBsB68vMR59HKYzwY1wKGdH6BdvJ34UuHBH7E7tr6hkbK6wPhoJAaJsoUP93EDMxeSai06Wgl0j-94EB9vyjaqJ9PT_g3OA9Zy1jbs4wancPgV8VBw-KygCgK0qo",
  },
];
